<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-FDD7CCMN" failures="1" tests="1" name="Test" time="9.175" errors="0" timestamp="2025-08-24T11:30:46 IST">
  <testcase classname="testCases.TC_003DDT" name="VerifyDDT" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.lang.ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 5">
      <![CDATA[java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 5
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 5
at utilities.DataProviders.getdata(DataProviders.java:26)
... 25 more
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- VerifyDDT -->
</testsuite> <!-- Test -->
